# Default values for localega.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
base:
  image: nbisweden/ega-base
  imageTag: latest
  imagePullPolicy: Always

config:
  deploy: true
  broker_host: ""
  broker_connection_attempts: 30
  broker_retry_delay: 10
  broker_username: ""
  cega_endpoint: "https://egatest.crg.eu/lega/v1/legas/users"
  cega_endpoint_json: "response.result"
  cega_mq_host: "hellgate.crg.eu"
  cega_vhost: ""
  cega_port: 5271
  cega_username: ""
  keyserver_host: ""
  postgres_db_name: "lega"
  postgres_host: ""
  postgres_try: 30
  postgres_user: ""
  data_storage_typ: "S3Storage"
  data_storage_url: ""

persistence: 
  enabled: true
## Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.

secrets:
  deploy: true
  mq_password: ""
  cega_creds: ""
  cega_mq_pass: ""
  keys_password: ""
  lega_password: ""
  mq_password: ""
  postgres_password: ""
  s3_access: ""
  s3_secret: ""

dataedge:
  name: dataedge
  replicaCount: 1
  repository: cscfi/ega-dataedge
  imageTag: "1.0"
  imagePullPolicy: Always
  port: 8080
  servicePort: 9059
  debug: 5058
  logpath: "/tmp/logs"

filedatabase:
  name: filedatabase
  replicaCount: 1
  repository: cscfi/ega-filedatabase
  imageTag: "1.0"
  imagePullPolicy: Always
  port: 8080
  servicePort: 9050
  debug: 5050

inbox:
  name: inbox
  repository: nbisweden/ega-inbox
  imageTag: latest
  imagePullPolicy: Always
  inboxPath: ""
  replicaCount: 1
  persistence:
    existingClaim: ""
    storageSize: 1Gi
    storageClass: flexVolume
    flexVolume:
      driver: ceph.rook.io/rook
      fsType: ceph
      fsName: sharedfs
      clusterNamespace: rook-ceph
  service:
    type: ClusterIP
    port: 2222

ingest:
  name: ingest
  replicaCount: 1

keys:
  deploy: true
  name: keys
  repository: cscfi/ega-keyserver
  imageTag: "1.0"
  imagePullPolicy: Always
  replicaCount: 1
  port: 8080
  servicePort: 9095
  debug: 5054

mapper:
  name: mapper
  replicaCount: 1

mq:
  name: mq
  repository: rabbitmq
  imageTag: 3.6-management-alpine
  imagePullPolicy: IfNotPresent
  replicaCount: 1
  persistence:
    existingClaim: ""
    storageSize: 1Gi
  port: 5672
  metrics:
    enabled: false
    repository: kbudde/rabbitmq-exporter
    imageTag: v0.29.0
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: 256Mi
        cpu: 100m

postgres:
  deploy: true
  name: db
  repository: postgres
  imageTag: 10-alpine
  imagePullPolicy: IfNotPresent
  persistence:
    existingClaim: ""
    storageSize: 1Gi
  replicaCount: 1
  metrics:
    enabled: false
    repository: wrouesnel/postgres_exporter
    imageTag: v0.4.6
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: 256Mi
        cpu: 100m

res:
  name: res
  repository: cscfi/ega-res
  imageTag: "1.0"
  imagePullpolicy: Always
  replicaCount: 1
  port: 8080
  servicePort: 9090
  debug: 5058

verify:
  name: verify
  replicaCount: 1
