appVersion: "1.0"
description: Fake CEGA for Local EGA
home: http://localega.readthedocs.io
icon: https://nbis.se/assets/img/logos/nbislogo-green.svg
maintainers:
name: cega
sources:
- https://github.com/NBISweden/LocalEGA-helm
version: 0.1.1
